
export const TokenPre = '';

export const TokenKey = 'Authorization';

export const IsNightKey = 'IsNightKey';

export const ThemeOptionsKey = 'ThemeOptionsKey';

export const IsFirstLogin = 'IsFirstLogin';

export const LockedKey = 'LockedKey';

export const salt = 'EIpWsyfiy@R@X#qn17!StJNdZK1fFF8iV6ffN!goZkqt#JxO';

export const aesKey = 'udpnpoc11aeskeym';

export const aesVi = 'udpnpoc11aesvii6';

// export const aesKey = 'udpnpoc9aeskeymd';

// export const aesVi = 'udpnpoc9aesviics';

export const loginTimeOutCode = 1012;

export const tokenErrorCode = 1010;


export const SideCollapsedMaxWidth = 700;

export const TopCollapsedMaxWidth = 1244;


export const TokenKeyDefault = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsicmVzMSJdLCJ1c2VyX25hbWUiOiJ7XCJhY2NvdW50Tm9uRXhwaXJlZFwiOnRydWUsXCJhY2NvdW50Tm9uTG9ja2VkXCI6dHJ1ZSxcImNsaWVudElkXCI6XCIxXCIsXCJjcmVkZW50aWFsc05vbkV4cGlyZWRcIjp0cnVlLFwiZW5hYmxlZFwiOnRydWUsXCJwYXNzd29yZFwiOlwiY2Y5YTMxOTM1NGI0OTM2ZWI4MGQwMzY3NGIxZjJkNGFcIixcInJlc291cmNlTGlzdFwiOltcIlIwXCIsXCJSMDJcIixcIlIwMjFcIixcIlIwMzIyXCIsXCJSMDMyXCIsXCJSMDNcIixcIlIwMjExXCIsXCJSMDMxXCIsXCJSMDIxNlwiLFwiUjAyMTNcIixcIlIwMjE3XCIsXCJSMDIxMlwiLFwiUjAyMTRcIixcIlIwMjE1XCIsXCJSMDQxXCIsXCJSMDQzXCIsXCJSMDRcIixcIlIwNDRcIixcIlIwNDVcIixcIlIwNDJcIixcIlIwNVwiLFwiUjA1MVwiLFwiUjA2MVwiLFwiUjA2MTJcIixcIlIwNjNcIixcIlIwNjMyXCIsXCJSMDYyXCIsXCJSMDYyMlwiLFwiUjA2NFwiLFwiUjA2NDJcIixcIlIwNjVcIixcIlIwNjU1XCIsXCJSMDY1NlwiLFwiUjA2NTRcIixcIlIwNjUzXCIsXCJSMDYxMVwiLFwiUjAxXCIsXCJSMDdcIixcIlIwNzFcIixcIlIwMTFcIixcIlIwMjE4XCIsXCJSMDMxMVwiLFwiUjAzMTJcIixcIlIwMzEzXCIsXCJSMDMxNFwiLFwiUjAzMTVcIixcIlIwMzE2XCIsXCJSMDMxN1wiLFwiUjAzMThcIixcIlIwMzIxXCIsXCJSMDMyM1wiLFwiUjAzMjRcIixcIlIwMzI1XCIsXCJSMDMyNlwiLFwiUjA2XCIsXCJSMDUyXCIsXCJSMDYyMVwiLFwiUjA2MzFcIixcIlIwNjQxXCIsXCJSMDY1MVwiLFwiUjA4XCIsXCJSMDgxXCIsXCJSMDgyXCIsXCJSMDgxMVwiLFwiUjA4MTJcIixcIlIwODEzXCIsXCJSMDgxNFwiLFwiUjA4MTVcIixcIlIwODE2XCIsXCJSMDgxN1wiLFwiUjA4MjFcIixcIlIwODIyXCIsXCJSMDgyM1wiLFwiUjA4MjRcIixcIlIwODI1XCIsXCJSMDgyNlwiLFwiUjAxMlwiXSxcInNhbHRcIjpcIjI4ZTVkMGZkMDQ3NTBiOTAzNDFkYzE0OWE3YTZlOTZlXCIsXCJ1c2VyUmVhbE5hbWVcIjpcIlN1cGVyQWRtaW5pc3RyYXRvclwiLFwidXNlcm5hbWVcIjpcImFkbWluXCJ9Iiwic2NvcGUiOlsiUk9MRV9BRE1JTiIsIlJPTEVfVVNFUiIsIlJPTEVfQVBJIl0sImV4cCI6MTY3Njg2MjE2NCwiYXV0aG9yaXRpZXMiOlsiUjAwMSJdLCJqdGkiOiI1NzYwOTdiMi1jYzM2LTQ1ZTktODkyOC1mMmM4MWFiMjlkZmEiLCJjbGllbnRfaWQiOiJjMSJ9.8j-hGtQuP5GLv00rKpsj-YXknAtH5io5_XL358JqR-4';